---
title: "Modelo_Junta"
author: "Alicia Xu díez"
format: html
editor: visual
---

## Modelo actual de JCyL

## librerías y datos a usar

(Pinus sylvestris, 21; Pinus nigra, 25; Pinus pinaster, 26; Quercus pyrenaica, 43). Como necesita variables de masa se emplearán los datos de "plots"

```{r}
library(ggplot2)    
library(psych)       
library(openxlsx)
library(minpack.lm)
library(datana)
#click en el archivo .rdata
plots <- read.csv("/home/alicia/Uni/TFG/forR/Data/Procesados/1_harmonized_plot_df_jcyl_sfni.csv")


plots <- plots[complete.cases(plots[, c("dg", "G", "h_mean", "dbh_mean", "Ho")]), ]
plots <- subset(plots, sp_1 == 21) 
str(plots)                                            #Ver estructura de datos
```

**Modelo y gráfica**

Paper del modelo: doi = {10.1007/BF02796077}

```{r}
modelo_junta_2001 <- nlsLM(
  h_mean ~ 1.3 + (b0 + b1 * Ho - b2 * dg + b3 * G) * exp(-b4 / sqrt(dbh_mean)),
  data = plots,
  start = list(
    b0 = 1,
    b1 = 0.5,
    b2 = 0.5,
    b3 = 0.1,
    b4 = 5
  ),
  control = nls.lm.control(
    maxiter = 500,
    ftol = 1e-10,
    ptol = 1e-10
  )
)

summary(modelo_junta_2001)

#Gráfica del modelo
plots$h_pred <- predict(modelo_junta_2001)

ggplot(plots, aes(x = dbh_mean, y = h_mean)) +
  geom_point(alpha = 0.6) +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
  labs(
    title = "Relación Altura-Diámetro. Modelo actual",
    subtitle = "Quercus pyrenaica",   #Para poner el nomebre en cursiva
    x = "Diámetro (cm)",
    y = "Altura (m)"
  ) +
  theme_minimal() + 
  theme(plot.subtitle = element_text(face = "italic", hjust = 0.5)) #Para poner el nombre en cursiva

#ggsave("/home/alicia/Uni/TFG/forR/Outputs/Q.pyrenaica/Modelo_Junta/Modelo_Junta_Psyl.png",dpi=300, width=12, height =8, unit="cm")

```

**Gráfico de residuales**

```{r}
#Gráfico de residuos
plots$residuos <- resid(modelo_junta_2001)

ggplot(plots, aes(x = h_pred, y = residuos)) +
  geom_point(alpha = 0.6) +
  geom_hline(yintercept = 0, color = "red") +
  labs(
    title = "Residuos del modelo actual",
    subtitle = "Quercus pyrenaica",   #Para poner el nomebre en cursiva
    x = "Altura predicha (m)",
    y = "Residuos (m)"
  ) +
  theme_minimal() + 
  theme(plot.subtitle = element_text(face = "italic", hjust = 0.5)) #Para poner el nombre en cursiva
    
#ggsave("/home/alicia/Uni/TFG/forR/Outputs/Q.pyrenaica/Modelo_Junta/Residual_Modelo_Junta_Psyl.png",dpi=300, width=12, height =8, unit="cm")
```

**Indicadores**

```{r}
##INDICADORES

  # RMSE
     RMSE <- sqrt(mean((plots$h_mean - plots$h_pred)^2))

    
  # R2
      R2 <- 1 - sum((plots$h_mean - plots$h_pred)^2) / sum((plots$h_mean - mean(plots$h_mean))^2)
              
  # AIC
      AIC_val <- AIC(modelo_junta_2001)
    
  # Mean Bias
      MB <- mean(plots$h_pred - plots$h_mean)
    
  # Tabla de resultados
      indices <- data.frame(
            RMSE = RMSE,
            R2   = R2,
            AIC  = AIC_val,
            MB   = MB,
            Modelo = "Junta_2001"
)

indices
```
