---
title: "Modelo h-d"
author: "Alicia Xu Díez"
format: html
editor: visual
---

## Modelo lineal sencillo

### Filtrado de especies

(*Pinus sylvestris*, 21; *Pinus nigra*, 25; *Pinus pinaster*, 26; *Quercus pyrenaica*, 43).

Archivo csv sin variables de masa

```{r}
library(tidyverse)  
library(ggplot2)    
library(psych)       
library(openxlsx)
library(minpack.lm)
trees <- read.csv("C:/Users/alicia/Desktop/TFG/data/Procesados/1_harmonized_tree_df_jcyl_sfni.csv")

str(trees)                                            #Ver estructura de datos
trees <- subset(trees, species == 43)     #Cambiar el 26 por cualquiera de los códigos mencionados anteriormente            
```

### Estadísticos

```{r}
# analisis estadistico
summary(trees[,c("dbh","h")])
trees <- trees[trees$dead == 0, ]
```

se eliminan los árboles muertos con h =0

```{r}
# Histograma altura

ggplot(trees, aes(x = h)) +
  geom_histogram(fill = "lightgreen", color = "darkgreen") +
  labs(
    title = "Histograma de Altura",
    x = "h (m)",
    y = "Frecuencia"
  )

ggsave("C:/Users/Alicia/Desktop/TFG/outputs/Modelo_sencillo/Q.pyrenaica/Histograma altura.png",dpi=300, width=12, height =8, unit="cm")
```

```{r}
# Histograma de Diametro

ggplot(trees, aes(x = h)) +
  geom_histogram(fill = "lightblue", color = "darkblue") +
  labs(
    title = "Histograma de diámetro",
    x = "dbh (cm)",
    y = "Frecuencia"
  )

ggsave("C:/Users/Alicia/Desktop/TFG/Outputs/Modelo_sencillo/Q.pyrenaica/Histograma diametro.png",dpi=300, width=12, height =8, unit="cm")

```

```{r}
#Gráfico de violín altura
ggplot(trees, aes(x = "", y = h)) +
  geom_violin(fill = "lightgreen", color = "darkgreen", trim = FALSE) +
  geom_boxplot(width = 0.1, fill = "white", outlier.color = NA) +  # Añade caja dentro del violín
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +  # Mostrar eje 0
  geom_vline(xintercept = 0, color = "red", linetype = "dashed") +
  expand_limits(x = 0, y = 0) +
  labs(
    title = "Distribución de la altura total de los árboles",
    x = "Conjunto de datos",
    y = "h (m)"
  ) +
  theme_minimal(base_size = 14)

ggsave("C:/Users/Alicia/Desktop/TFG/Outputs/Modelo_sencillo/Q.pyrenaica/Grafico de violín h.png",dpi=300, width=12, height =8, unit="cm")
```

```{r}
#Gráfico de violín diámetro
ggplot(trees, aes(x = "", y = dbh)) +
  geom_violin(fill = "lightblue", color = "darkblue", trim = FALSE) +
  geom_boxplot(width = 0.1, fill = "white", outlier.color = NA) +  # Añade caja dentro del violín
  geom_hline(yintercept = 0, color = "red", linetype = "dashed") +  # Mostrar eje 0
  geom_vline(xintercept = 0, color = "red", linetype = "dashed") +
  expand_limits(x = 0, y = 0) +
  labs(
    title = "Distribución del diámetro de los árboles",
    x = "Conjunto de datos",
    y = "dbh (cm)"
  ) +
  theme_minimal(base_size = 14)

ggsave("C:/Users/Alicia/Desktop/TFG/Outputs/Modelo_sencillo/Q.pyrenaica/Grafico de violin dbh.png",dpi=300, width=12, height =8, unit="cm")
```

Mirar pq la frecuencia de las h en P.pinaster, P.nigra y P. sylvestris

### Modelo lineal

```{r}
modelo_lineal <- lm(h ~ dbh, data = trees)

# Ver resumen del modelo
summary(modelo_lineal)
```

```{r}
dbh_seq <- seq(min(trees$dbh), max(trees$dbh), length.out = 1000)
pred_h <- predict(modelo_lineal, newdata = data.frame(dbh = dbh_seq))

df_artificial <- data.frame(dbh_seq, pred_h)

# --- 6. Graficar la relación altura-diámetro ----
ggplot(trees, aes(x = dbh, y = h)) +
  geom_point(color = "forestgreen", size = 2, alpha = 0.6) +  # Puntos de los árboles
  geom_point(data = df_artificial, aes(x = dbh_seq, y = pred_h), color = 'red')+
  xlim(0, max(trees$dbh)) +
  ylim(0, max(trees$h)) +
  labs(
    title = "Relación Altura-Diámetro. Modelo lineal",
    subtitle = "Quercus pyrenaica",   #Para poner el nomebre en cursiva
    x = "Diámetro (cm)",
    y = "Altura (m)"
  ) +
  theme_minimal() + 
  theme(plot.subtitle = element_text(face = "italic", hjust = 0.5)) #Para poner el nombre en cursiva

ggsave("C:/Users/Alicia/Desktop/TFG/Outputs/Modelo_sencillo/Q.pyrenaica/Modelo lineal.png",dpi=300, width=12, height =8, unit="cm")
```

### Calidad del ajuste

```{r}
pred_obs <- predict(modelo_lineal, newdata = trees)

# RMSE
RMSE <- sqrt(mean((trees$h - pred_obs)^2))

# R2
R2 <- summary(modelo_lineal)$r.squared

# AIC
AIC_value <- AIC(modelo_lineal)

# Mean Bias
MB <- mean(pred_obs - trees$h)

# Tabla de resultados
resultados <- data.frame(
  RMSE = RMSE,
  R2 = R2,
  AIC = AIC_value,
  MB = MB
)

resultados

```

En base a estos valores, podemos decir no es/es un mal ajuste

```{r}

# 7.6 Valores residuales ####
#El modelo se ajustará mejor a los datos según la forma de la nuve de puntos. La línaea del "cero"
#debería quedar en mitad de toda esa nube sin que esta haga forma de cono, o se incline hacia arriba/abajo

# --- 1. Calcular residuales y predicciones ---
residuales <- residuals(modelo_lineal)
predicciones <- fitted(modelo_lineal)

# --- 2. Gráfico de residuales vs predicciones ---
ggplot(data.frame(predicciones, residuales), aes(x = predicciones, y = residuales)) +
  geom_point(color = "forestgreen", size = 2, alpha = 0.7) +
  geom_hline(yintercept = 0, color = "red", linewidth = 1, linetype = "dashed") +
  labs(
    title = "Residuales vs Predicciones",
    x = "Altura predicha (m)",
    y = "Residuales (m)"
  ) +
  theme_minimal()

ggsave("C:/Users/Alicia/Desktop/TFG/Outputs/Modelo_sencillo/Q.pyrenaica/Residuales.png",dpi=300, width=12, height =8, unit="cm")
```
